grades_app/urls.py
from django.urls import path
from . import views 

app_name = "grades_app"

urlpatterns = [

	path('', views.index, name="index"),
	path('grades_app/<int:student_id>/', views.student_detail, name='student_detail'),
	path("grades", views.subject_grades, name="subject_grades"),

	# path("grade_choice", views.grade_choice, name="grade_choice"),
	# path("math_averages_9", views.math_averages_9, name="average_list_9"),
	# path("math_averages_10", views.math_averages_10, name="average_list_10"),

	path("math_average/<int:grade_level>", views.math_average, name="math_average"),
	path("english_average/<int:grade_level>", views.english_average, name="english_average"),

	path("math_generate_report/<int:grade_level>", views.math_generate_report, name="math_generate_report"),
	path("english_generate_report/<int:grade_level>", views.english_generate_report, name="english_generate_report"),
	# path("en_chart", views.en_chart, name="en_chart"),




]

src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("grades_app.urls", namespace="grades_app")),
    path('accounts/', include('django.contrib.auth.urls',)), # new
    
]

grades_app/models.py
from django.db import models
from src.settings import AUTH_USER_MODEL
from django.contrib.auth.models import Group
from django.utils.translation import gettext_lazy as _

GROUP_CHOICES = (
    ('High School Math Teachers', _('High School Math Teachers')),
    ('High School English Teachers', _('High School English Teachers')),
    ('High School Chemistry Teachers', _('High School Chemistry Teachers')),
    ('High School Physics Teachers', _('High School Physics Teachers')),

    # Add more choices as needed
)

class CustomGroup(Group):
    class Meta:
        proxy = True
        verbose_name_plural = "Groups"

    def __str__(self):
        return self.name



    # Add any additional methods or properties as needed

class CustomGroupData(models.Model):
    group = models.OneToOneField(
        Group,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='custom_data'
    )
    name = models.CharField(_('name'), max_length=50, unique=True, choices=GROUP_CHOICES)

    # Add any additional fields or methods as needed

class Student(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    grade_level = models.IntegerField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Math_Grade_9(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "Math Grade 9"

    def __str__(self):
        return f"{self.grade}"

class Math_Grade_10(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "Math Grade 10"

    def __str__(self):
        return f"{self.grade}"

class Math_Grade_11(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "Math Grade 11"

    def __str__(self):
        return f"{self.grade}"

class Math_Grade_12(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "Math Grade 12"

    def __str__(self):
        return f"{self.grade}"

class English_Grade_9(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "English Grade 9"

    def __str__(self):
        return f"{self.grade}"

class English_Grade_10(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "English Grade 10"

    def __str__(self):
        return f"{self.grade}"

class English_Grade_11(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "English Grade 11"

    def __str__(self):
        return f"{self.grade}"

class English_Grade_12(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE,)
    date = models.DateField()
    grade = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        verbose_name_plural = "English Grade 12"


    def __str__(self):
        return f"{self.grade}"

grades_app/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model

from django.contrib.auth.decorators import login_required
from .models import *
from django.db.models import Count, Avg
from django.http import HttpResponse
from django.urls import reverse

from django.contrib.auth.decorators import user_passes_test

import pdfkit
import csv

CustomUser = get_user_model()


# The Index Function
def index(request):


	user_groups = request.user.groups.values_list('name', flat=True)

	in_math_group = None
	in_english_group = None

	if 'High School Math Teachers' in user_groups:
		in_math_group = "High School Math Teachers"
	elif "High School English Teachers" in user_groups:
		in_english_group = 'High School English Teachers' in user_groups

	context = {
		
		'in_math_group': in_math_group,
		'in_english_group' : in_english_group,

	}
	return render(request, 'grades_app/index.html', context)

@login_required
def student_detail(request):
    if not request.user.is_staff:
        student = get_object_or_404(Student, user=request.user)
        return render(request, 'grades_app/student_detail.html', {'student': student})
    else:
        # Handle the case if the logged-in user is not a student
        return render(request, 'grades_app/access_denied.html')

@login_required
def subject_grades(request):
	student = request.user.student

	math_grade_of_student_9 = Math_Grade_9.objects.filter(student=student).aggregate(Avg('grade'))
	math_grade_of_student_10 = Math_Grade_10.objects.filter(student=student).aggregate(Avg('grade'))
	math_grade_of_student_11 = Math_Grade_11.objects.filter(student=student).aggregate(Avg('grade'))
	math_grade_of_student_12 = Math_Grade_12.objects.filter(student=student).aggregate(Avg('grade'))

	english_grade_of_student_9 = English_Grade_9.objects.filter(student=student).aggregate(Avg('grade'))
	english_grade_of_student_10 = English_Grade_10.objects.filter(student=student).aggregate(Avg('grade'))
	english_grade_of_student_11 = English_Grade_11.objects.filter(student=student).aggregate(Avg('grade'))
	english_grade_of_student_12 = English_Grade_12.objects.filter(student=student).aggregate(Avg('grade'))

	math_average_9 = math_grade_of_student_9["grade__avg"] 
	math_average_10 = math_grade_of_student_10["grade__avg"] 
	math_average_11 = math_grade_of_student_11["grade__avg"] 
	math_average_12 = math_grade_of_student_12["grade__avg"] 

	english_average_9 = english_grade_of_student_9["grade__avg"]
	english_average_10 = english_grade_of_student_10["grade__avg"]
	english_average_11 = english_grade_of_student_11["grade__avg"]
	english_average_12 = english_grade_of_student_12["grade__avg"]

	context = {

		"student": student,
		
		"math_grades_9" : Math_Grade_9.objects.filter(student=student).order_by("-date"),
		"math_grades_10" : Math_Grade_10.objects.filter(student=student).order_by("-date"),
		"english_grades_9" : English_Grade_9.objects.filter(student=student).order_by("-date"),
		"english_grades_10" : English_Grade_10.objects.filter(student=student).order_by("-date"),

		"math_average_9" : math_average_9,
		"math_average_10" : math_average_10,
		"math_average_11" : math_average_11,
		"math_average_12" : math_average_12,

		"english_average_9" : english_average_9,
		"english_average_10" : english_average_10,
		"english_average_11" : english_average_11,
		"english_average_12" : english_average_12,


	}
	return render(request, 'grades_app/list_grades.html', context)

def calculate_average_math_grade(student, grade_level):


    if grade_level == 9:
        grade_model = Math_Grade_9
    elif grade_level == 10:
        grade_model = Math_Grade_10
    elif grade_level == 11:
        grade_model = Math_Grade_11
    elif grade_level == 12:
        grade_model = Math_Grade_12
    else:
        return 0
    
    math_grades = grade_model.objects.filter(student=student)
    total_grades = math_grades.count()
    
    if total_grades > 0:
        total_sum = sum(grade.grade for grade in math_grades)
        average_grade = total_sum / total_grades
        return average_grade
    else:
        return 0

def calculate_average_english_grade(student, grade_level):


    if grade_level == 9:
        grade_model = English_Grade_9
    elif grade_level == 10:
        grade_model = English_Grade_10
    elif grade_level == 11:
        grade_model = English_Grade_11
    elif grade_level == 12:
        grade_model = English_Grade_12
    else:
        return 0
    
    english_grades = grade_model.objects.filter(student=student)
    total_grades = english_grades.count()
    
    if total_grades > 0:
        total_sum = sum(grade.grade for grade in english_grades)
        average_grade = total_sum / total_grades
        return average_grade
    else:
        return 0


@login_required
@user_passes_test(lambda user: user.groups.filter(name='High School Math Teachers').exists())
def math_average(request, grade_level):


	students = Student.objects.filter(grade_level=grade_level)
	student_grades_list = []

	grade_levels = [9, 10, 11, 12]

	for student in students:
		average_grade = calculate_average_math_grade(student, grade_level)
		student_grades_list.append((student.first_name, student.last_name, average_grade))

	context = {
		'student_grades_list': student_grades_list,
		'grade_level': grade_level,
		'grade_levels': grade_levels,
		
	}

	return render(request, 'grades_app/math_averages.html', context)


@login_required
@user_passes_test(lambda user: user.groups.filter(name='High School English Teachers').exists())
def english_average(request, grade_level):


	students = Student.objects.filter(grade_level=grade_level)
	student_grades_list_english = []

	grade_levels = [9, 10, 11, 12]

	for student in students:
		average_grade = calculate_average_english_grade(student, grade_level)
		student_grades_list_english.append((student.first_name, student.last_name, average_grade))

	grades_to_chart = []
	for grades in student_grades_list_english:
		# grades_to_chart = []
		whatever = grades[2]
		grades_to_chart.append(whatever)
	# print(grades_to_chart)
	grades_to_chart = grades_to_chart
		
		

	context = {
		'student_grades_list': student_grades_list_english,
		'grade_level': grade_level,
		'grade_levels': grade_levels,
		'grades_to_chart': grades_to_chart,
		
	}


	return render(request, 'grades_app/english_averages.html', context)


# All the Report generate functions

@login_required
@user_passes_test(lambda user: user.groups.filter(name='High School Math Teachers').exists())
def math_generate_report(request, grade_level):


	students = Student.objects.filter(grade_level=grade_level)
	student_grades_list = []

	grade_levels = [9, 10, 11, 12]

	for student in students:
		average_grade = calculate_average_math_grade(student, grade_level)
		student_grades_list.append((student.first_name, student.last_name, average_grade))
	
	


	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = f'attachment; filename="Math Average Grade {grade_level}.csv"'

	# response = HttpResponse(content_type='text/csv', headers={'Content-Disposition': 'attachment; filename="Math_Average.csv"'},)
	writer = csv.writer(response)
	writer.writerow(['First Name', "Last Name", 'Average Grade',])

	for student in student_grades_list:
		writer.writerow([f"{student[0]}", f"{student[1]}", f"{student[2]}"])
	return response


@login_required
@user_passes_test(lambda user: user.groups.filter(name='High School English Teachers').exists())
def english_generate_report(request, grade_level):


	students = Student.objects.filter(grade_level=grade_level)
	student_grades_list = []

	grade_levels = [9, 10, 11, 12]

	for student in students:
		average_grade = calculate_average_english_grade(student, grade_level)
		student_grades_list.append((student.first_name, student.last_name, average_grade))
	
	


	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = f'attachment; filename="English Average Grade {grade_level}.csv"'

	# response = HttpResponse(content_type='text/csv', headers={'Content-Disposition': 'attachment; filename="Math_Average.csv"'},)
	writer = csv.writer(response)
	writer.writerow(['First Name', "Last Name", 'Average Grade',])

	for student in student_grades_list:
		writer.writerow([f"{student[0]}", f"{student[1]}", f"{student[2]}"])
	return response

grades_app/templates/grades_app/english_averages.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="nTek">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Student · Grades</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'grades_app/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'grades_app/all.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'grades_app/Chart.min.css' %}">
    <script src="{% static 'grades_app/Chart.js' %}"></script>
    <script src="{% static 'grades_app/Chart.min.js' %}"></script>
    <style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <h1 class="navbar-brand h1" href="#">English</h1>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    {% for grade_level in grade_levels %}
                    <li style="padding-left: 5px; padding-bottom: 3px;" class="nav-item">
                        <a class="nav-item btn btn-outline-light" aria-current="page" href="{% url 'grades_app:english_average' grade_level=grade_level %}">Grade {{ grade_level }}</a>
                    </li>
                    {% endfor %}
                    <div style="padding-left: 5px; padding-bottom: 3px;" class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle btn btn-outline-success" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-file-csv"></i> Report
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                    <li><h6 class="dropdown-header">Generate Report</h6></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 9 %}">Grade 9</a></li>
                                    <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 10 %}">Grade 10</a></li>
                                    <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 11 %}">Grade 11</a></li>
                                    <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 12 %}">Grade 12</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div style="padding-left: 5px; padding-bottom: 3px;" class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle btn btn-outline-primary" href="#" id="dropdown03" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="fa fa-user-circle"></i> {{ request.user.username | title }}</a>
                                <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                    <li><h6 class="dropdown-header">User actions</h6></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'admin:index' %}"><i class="fa fa-database"></i> Panel</a></li>
                                    <li><a class="dropdown-item" href="{% url 'password_change' %}"><i class="fa fa-lock"></i> Change Password</a></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </ul>
            </div>
        </div>
    </nav>
    <main class="container">
        <div class="bg-light p-5 rounded">
            <h2 style="text-align:center;" class="mt-4"><strong>Grade {{ grade_level }}</strong></h2>
            <div class="bd-cheatsheet container-fluid bg-body">
                <section id="content">
                    <article class="my-3" id="tables">
                        <div>
                            <div class="bd-example">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th class="table-dark">First Name</th>
                                            <th class="table-dark">Last Name</th>
                                            <th class="table-dark">Average English Grade</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for student in student_grades_list %}
                                        <tr>
                                            {% for value in student %}
                                            <td>{{ value }}</td>
                                            {% endfor %}
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </article>
                </section>
            </div>
            <!-- <canvas id="myChart" width="40" height="40"></canvas> -->
    <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                // labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                labels: ["Failing", "Midlevel", "Passing",],
                datasets: [{
                    label: 'Percentages',
                    // data: [12, 19, 3,],
                    data: [{% for data in grades_to_chart %} {{data}}, {% endfor %}],
                    backgroundColor: [

                        'rgba(255, 0, 0, 0.2)',
                        'rgba(0, 255, 0, 0.2)',
                        'rgba(0, 0, 255, 0.2)',
                        // 'rgba(255, 99, 132, 0.2)',
                        // 'rgba(42, 99, 45, 0.2)',
                        // 'rgba(79, 99, 132, 0.2)',


                    ],
                    borderColor: [

                        'rgba(255, 99, 132, 0.2)', 
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',


                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
        </div>
    </main>
    <script src="{% static 'grades_app/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

grades_app/templates/grades_app/english_averages_copy.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Student Grades</title>
</head>
<link rel="stylesheet" type="text/css" href="{% static 'grades_app/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'grades_app/all.css' %}">
<!-- <link rel="stylesheet" type="text/css" href="{% static 'grades_app/all.min.css' %}"> -->

<body class="container">
    <h1>English Averages</h1>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="bd-example">
                    {% for grade_level in grade_levels %}
                    <a class="btn btn-outline-light" href="{% url 'grades_app:english_average' grade_level=grade_level %}">Grade {{ grade_level }}</a>
                    {% endfor %}
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary"><i class="fas fa-file-csv" aria-hidden="true"></i> Report</button>
                        <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 9 %}">Grade 9</a></li>
                            <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 10 %}">Grade 10</a></li>
                            <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 11 %}">Grade 11</a></li>
                            <li><a class="dropdown-item" href="{% url 'grades_app:english_generate_report' 12 %}">Grade 12</a></li>
                        </ul>
                    </div>
                    <!-- <a class="btn btn-danger" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> Logout</a> -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-secondary"><i class="fa fa-user-circle" aria-hidden="true"></i> {{ request.user.username }}</button>
                        <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="visually-hidden">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}"><i class="fa fa-database"></i> Panel</a></li>
                            <li><a class="dropdown-item" href="{% url 'password_change' %}"><i class="fa fa-lock"></i> Change Password</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt" aria-hidden="true"></i> Logout</a></li>
                        </ul>
                    </div>

                </div>


            </div>
            
            

        </div>
    </nav>
    <h2 style="text-align:center;" class="mt-4"><strong>Grade {{ grade_level }}</strong></h2>
    <div class="bd-cheatsheet container-fluid bg-body">
        <section id="content">
            <article class="my-3" id="tables">
                <div>
                    <div class="bd-example">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="table-dark">First Name</th>
                                    <th class="table-dark">Last Name</th>
                                    <th class="table-dark">Average English Grade</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for student in student_grades_list %}
                                <tr>
                                    {% for value in student %}
                                    <td>{{ value }}</td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </article>
        </section>
    </div>
</body>
<script src="{% static 'grades_app/bootstrap.bundle.min.js' %}"></script>

</html>

grades_app/templates/grades_app/index.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="nTek">
        <title>Welcome</title>
        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/cover/">
        <!-- Bootstrap and other core CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'grades_app/bootstrap.min.css' %}">
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'grades_app/font-awesome.min.css' %}"> -->
        <link rel="stylesheet" type="text/css" href="{% static 'grades_app/all.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'grades_app/all.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'grades_app/brands.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'grades_app/brands.min.css' %}">
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'grades_app/delete.css' %}"> -->
        
        <style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
        }
        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
        font-size: 3.5rem;
        }
        }
        </style>
        <!-- Custom styles for this template -->
        <link href="{% static 'grades_app/cover.css' %}" rel="stylesheet">
    </head>
    <body class="d-flex h-100 text-center text-white bg-dark">
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
            <header class="mb-auto">
                <div>
                    {# <h3 class="float-md-start mb-0"><i class="fa fa-bolt"></i> PowerGrid</h3> #}
                    <h3 class="float-md-start mb-0"><img style="width: 30px; height: 60px" src="{% static 'grades_app/icon.ico' %}"></h3>

                    <nav class="nav nav-masthead justify-content-center float-md-end">
                        {% if user.is_authenticated %}
                            <a class="nav-link" href=""><i class="fas fa-user-circle" aria-hidden="true"></i>
                            {{ request.user }}</a>
                            <a class="nav-link active" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                            Logout</a>
                            {% if user.is_staff %}
                                <a class="nav-link active" href="{% url 'admin:index' %}"><i class="fa fa-database" aria-hidden="true"></i>
                                Panel</a>
                                
                                {% if in_math_group %}
                                    <a class="nav-link active" href="{% url 'grades_app:math_average' 9%}"><i class="fa fa-percent" aria-hidden="true"></i> Averages</a>
                                    {% elif in_english_group %}
                                    <a class="nav-link active" href="{% url 'grades_app:english_average' 9%}"><i class="fa fa-percent" aria-hidden="true"></i> Averages</a>
                                {% endif %}
                                {% elif not user.is_staff %}
                                <a class="nav-link active" href="{% url 'grades_app:subject_grades' %}"><i class="fa fa-graduation-cap" aria-hidden="true"></i> Grades</a>
                            {% endif %}
                        {% else %}
                            <a class="nav-link active" href="{% url 'login' %}"><i class="fas fa-sign-in-alt" aria-hidden="true"></i> Login</a>
                        {% endif %}
                    </nav>
                </div>
            </header>
            <main class="px-3">
                <!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" width="100" height="100">
                    <path fill="#ffffff" d="M296 160H180.6l42.6-129.8C227.2 15 215.7 0 200 0H56C44 0 33.8 8.9 32.2 20.8l-32 240C-1.7 275.2 9.5 288 24 288h118.7L96.6 482.5c-3.6 15.2 8 29.5 23.3 29.5 8.4 0 16.4-4.4 20.8-12l176-304c9.3-15.9-2.2-36-20.7-36z" /></svg> -->

                    <img style="margin-top: 16px;" src="{% static 'grades_app/logo.png' %}">
                    <h1 style="font-size: 40px;">Welcome to <strong>PowerGrid</strong>!</h1>
                    <p style="font-size: 20px;" class="lead">Powergrid is a one-for-all CMS for making your life as a teacher super easy. Focus on teaching and let PowerGrid do the rest. So why the lag? Login and explore PowerGrid at work!</p>
                </main>
                <footer class="mt-auto text-white-50">
                    <p><i class="fa fa-copyright" aria-hidden="true"></i>
                    nTek 2024</p>
                </footer>
            </div>
        </body>
    </html>